ES sched1
E s0(sched1)
Restrict s0 init1
-0.13 -- P{s0}[F "d0"] <= P{s0}[F "d1"]
-0.13 -- P{s0}[F "d1"] <= P{s0}[F "d0"]
-0.13 -- P{s0}[F "d1"] <= P{s0}[F "d2"]
-0.13 -- P{s0}[F "d2"] <= P{s0}[F "d1"]
-0.13 -- P{s0}[F "d2"] <= P{s0}[F "d3"]
-0.13 -- P{s0}[F "d3"] <= P{s0}[F "d2"]
-0.13 -- P{s0}[F "d3"] <= P{s0}[F "d4"]
-0.13 -- P{s0}[F "d4"] <= P{s0}[F "d3"]
-0.13 -- P{s0}[F "d4"] <= P{s0}[F "d5"]
-0.13 -- P{s0}[F "d5"] <= P{s0}[F "d4"]
-0.13 -- P{s0}[F "d5"] <= P{s0}[F "d6"]
-0.13 -- P{s0}[F "d6"] <= P{s0}[F "d5"]
-0.13 -- P{s0}[F "d6"] <= P{s0}[F "d7"]
-0.13 -- P{s0}[F "d7"] <= P{s0}[F "d6"]
-0.13 -- P{s0}[F "d7"] <= P{s0}[F "d8"]
-0.13 -- P{s0}[F "d8"] <= P{s0}[F "d7"]
-0.13 -- P{s0}[F "d8"] <= P{s0}[F "d9"]
-0.13 -- P{s0}[F "d9"] <= P{s0}[F "d8"]
-0.13 -- P{s0}[F "d9"] <= P{s0}[F "d10"]
-0.13 -- P{s0}[F "d10"] <= P{s0}[F "d9"]
-0.13 -- P{s0}[F "d10"] <= P{s0}[F "d11"]
-0.13 -- P{s0}[F "d11"] <= P{s0}[F "d10"]
-0.13 -- P{s0}[F "d11"] <= P{s0}[F "d12"]
-0.13 -- P{s0}[F "d12"] <= P{s0}[F "d11"]
-0.13 -- P{s0}[F "d12"] <= P{s0}[F "d13"]
-0.13 -- P{s0}[F "d13"] <= P{s0}[F "d12"]
-0.13 -- P{s0}[F "d13"] <= P{s0}[F "d14"]
-0.13 -- P{s0}[F "d14"] <= P{s0}[F "d13"]
-0.13 -- P{s0}[F "d14"] <= P{s0}[F "d15"]
-0.13 -- P{s0}[F "d15"] <= P{s0}[F "d14"]
-0.13 -- P{s0}[F "d15"] <= P{s0}[F "d16"]
-0.13 -- P{s0}[F "d16"] <= P{s0}[F "d15"]
-0.13 -- P{s0}[F "d16"] <= P{s0}[F "d17"]
-0.13 -- P{s0}[F "d17"] <= P{s0}[F "d16"]
-0.13 -- P{s0}[F "d17"] <= P{s0}[F "d18"]
-0.13 -- P{s0}[F "d18"] <= P{s0}[F "d17"]
-0.13 -- P{s0}[F "d18"] <= P{s0}[F "d19"]
-0.13 -- P{s0}[F "d19"] <= P{s0}[F "d18"]
-0.13 -- P{s0}[F "d19"] <= P{s0}[F "d20"]
-0.13 -- P{s0}[F "d20"] <= P{s0}[F "d19"]
-0.13 -- P{s0}[F "d20"] <= P{s0}[F "d21"]
-0.13 -- P{s0}[F "d21"] <= P{s0}[F "d20"]
-0.13 -- P{s0}[F "d21"] <= P{s0}[F "d22"]
-0.13 -- P{s0}[F "d22"] <= P{s0}[F "d21"]
-0.13 -- P{s0}[F "d22"] <= P{s0}[F "d23"]
-0.13 -- P{s0}[F "d23"] <= P{s0}[F "d22"]
-0.13 -- P{s0}[F "d23"] <= P{s0}[F "d24"]
-0.13 -- P{s0}[F "d24"] <= P{s0}[F "d23"]
-0.13 -- P{s0}[F "d24"] <= P{s0}[F "d25"]
-0.13 -- P{s0}[F "d25"] <= P{s0}[F "d24"]
-0.13 -- P{s0}[F "d25"] <= P{s0}[F "d26"]
-0.13 -- P{s0}[F "d26"] <= P{s0}[F "d25"]
-0.13 -- P{s0}[F "d26"] <= P{s0}[F "d27"]
-0.13 -- P{s0}[F "d27"] <= P{s0}[F "d26"]
-0.13 -- P{s0}[F "d27"] <= P{s0}[F "d28"]
-0.13 -- P{s0}[F "d28"] <= P{s0}[F "d27"]
-0.13 -- P{s0}[F "d28"] <= P{s0}[F "d29"]
-0.13 -- P{s0}[F "d29"] <= P{s0}[F "d28"]
-0.13 -- P{s0}[F "d29"] <= P{s0}[F "d30"]
-0.13 -- P{s0}[F "d30"] <= P{s0}[F "d29"]
-0.13 -- P{s0}[F "d30"] <= P{s0}[F "d31"]
-0.13 -- P{s0}[F "d31"] <= P{s0}[F "d30"]
-0.13 -- P{s0}[F "d31"] <= P{s0}[F "d32"]
-0.13 -- P{s0}[F "d32"] <= P{s0}[F "d31"]
-0.13 -- P{s0}[F "d32"] <= P{s0}[F "d33"]
-0.13 -- P{s0}[F "d33"] <= P{s0}[F "d32"]
-0.13 -- P{s0}[F "d33"] <= P{s0}[F "d34"]
-0.13 -- P{s0}[F "d34"] <= P{s0}[F "d33"]
-0.13 -- P{s0}[F "d34"] <= P{s0}[F "d35"]
-0.13 -- P{s0}[F "d35"] <= P{s0}[F "d34"]
-0.13 -- P{s0}[F "d35"] <= P{s0}[F "d36"]
-0.13 -- P{s0}[F "d36"] <= P{s0}[F "d35"]
-0.13 -- P{s0}[F "d36"] <= P{s0}[F "d37"]
-0.13 -- P{s0}[F "d37"] <= P{s0}[F "d36"]
-0.13 -- P{s0}[F "d37"] <= P{s0}[F "d38"]
-0.13 -- P{s0}[F "d38"] <= P{s0}[F "d37"]
-0.13 -- P{s0}[F "d38"] <= P{s0}[F "d39"]
-0.13 -- P{s0}[F "d39"] <= P{s0}[F "d38"]
-0.13 -- P{s0}[F "d39"] <= P{s0}[F "d40"]
-0.13 -- P{s0}[F "d40"] <= P{s0}[F "d39"]
-0.13 -- P{s0}[F "d40"] <= P{s0}[F "d41"]
-0.13 -- P{s0}[F "d41"] <= P{s0}[F "d40"]
-0.13 -- P{s0}[F "d41"] <= P{s0}[F "d42"]
-0.13 -- P{s0}[F "d42"] <= P{s0}[F "d41"]
-0.13 -- P{s0}[F "d42"] <= P{s0}[F "d43"]
-0.13 -- P{s0}[F "d43"] <= P{s0}[F "d42"]
-0.13 -- P{s0}[F "d43"] <= P{s0}[F "d44"]
-0.13 -- P{s0}[F "d44"] <= P{s0}[F "d43"]
-0.13 -- P{s0}[F "d44"] <= P{s0}[F "d45"]
-0.13 -- P{s0}[F "d45"] <= P{s0}[F "d44"]
-0.13 -- P{s0}[F "d45"] <= P{s0}[F "d46"]
-0.13 -- P{s0}[F "d46"] <= P{s0}[F "d45"]
-0.13 -- P{s0}[F "d46"] <= P{s0}[F "d47"]
-0.13 -- P{s0}[F "d47"] <= P{s0}[F "d46"]
-0.13 -- P{s0}[F "d47"] <= P{s0}[F "d48"]
-0.13 -- P{s0}[F "d48"] <= P{s0}[F "d47"]
-0.13 -- P{s0}[F "d48"] <= P{s0}[F "d49"]
-0.13 -- P{s0}[F "d49"] <= P{s0}[F "d48"]
-0.13 -- P{s0}[F "d49"] <= P{s0}[F "d50"]
-0.13 -- P{s0}[F "d50"] <= P{s0}[F "d49"]
-0.13 -- P{s0}[F "d50"] <= P{s0}[F "d51"]
-0.13 -- P{s0}[F "d51"] <= P{s0}[F "d50"]
-0.13 -- P{s0}[F "d51"] <= P{s0}[F "d52"]
-0.13 -- P{s0}[F "d52"] <= P{s0}[F "d51"]
-0.13 -- P{s0}[F "d52"] <= P{s0}[F "d53"]
-0.13 -- P{s0}[F "d53"] <= P{s0}[F "d52"]
-0.13 -- P{s0}[F "d53"] <= P{s0}[F "d54"]
-0.13 -- P{s0}[F "d54"] <= P{s0}[F "d53"]
-0.13 -- P{s0}[F "d54"] <= P{s0}[F "d55"]
-0.13 -- P{s0}[F "d55"] <= P{s0}[F "d54"]
-0.13 -- P{s0}[F "d55"] <= P{s0}[F "d56"]
-0.13 -- P{s0}[F "d56"] <= P{s0}[F "d55"]
-0.13 -- P{s0}[F "d56"] <= P{s0}[F "d57"]
-0.13 -- P{s0}[F "d57"] <= P{s0}[F "d56"]
-0.13 -- P{s0}[F "d57"] <= P{s0}[F "d58"]
-0.13 -- P{s0}[F "d58"] <= P{s0}[F "d57"]
-0.13 -- P{s0}[F "d58"] <= P{s0}[F "d59"]
-0.13 -- P{s0}[F "d59"] <= P{s0}[F "d58"]
-0.13 -- P{s0}[F "d59"] <= P{s0}[F "d60"]
-0.13 -- P{s0}[F "d60"] <= P{s0}[F "d59"]
-0.13 -- P{s0}[F "d60"] <= P{s0}[F "d61"]
-0.13 -- P{s0}[F "d61"] <= P{s0}[F "d60"]
-0.13 -- P{s0}[F "d61"] <= P{s0}[F "d62"]
-0.13 -- P{s0}[F "d62"] <= P{s0}[F "d61"]
-0.13 -- P{s0}[F "d62"] <= P{s0}[F "d63"]
-0.13 -- P{s0}[F "d63"] <= P{s0}[F "d62"]
-0.13 -- P{s0}[F "d63"] <= P{s0}[F "d64"]
-0.13 -- P{s0}[F "d64"] <= P{s0}[F "d63"]
-0.13 -- P{s0}[F "d64"] <= P{s0}[F "d65"]
-0.13 -- P{s0}[F "d65"] <= P{s0}[F "d64"]
-0.13 -- P{s0}[F "d65"] <= P{s0}[F "d66"]
-0.13 -- P{s0}[F "d66"] <= P{s0}[F "d65"]
-0.13 -- P{s0}[F "d66"] <= P{s0}[F "d67"]
-0.13 -- P{s0}[F "d67"] <= P{s0}[F "d66"]
-0.13 -- P{s0}[F "d67"] <= P{s0}[F "d68"]
-0.13 -- P{s0}[F "d68"] <= P{s0}[F "d67"]
-0.13 -- P{s0}[F "d68"] <= P{s0}[F "d69"]
-0.13 -- P{s0}[F "d69"] <= P{s0}[F "d68"]
-0.13 -- P{s0}[F "d69"] <= P{s0}[F "d70"]
-0.13 -- P{s0}[F "d70"] <= P{s0}[F "d69"]
-0.13 -- P{s0}[F "d70"] <= P{s0}[F "d71"]
-0.13 -- P{s0}[F "d71"] <= P{s0}[F "d70"]
-0.13 -- P{s0}[F "d71"] <= P{s0}[F "d72"]
-0.13 -- P{s0}[F "d72"] <= P{s0}[F "d71"]
-0.13 -- P{s0}[F "d72"] <= P{s0}[F "d73"]
-0.13 -- P{s0}[F "d73"] <= P{s0}[F "d72"]
-0.13 -- P{s0}[F "d73"] <= P{s0}[F "d74"]
-0.13 -- P{s0}[F "d74"] <= P{s0}[F "d73"]
-0.13 -- P{s0}[F "d74"] <= P{s0}[F "d75"]
-0.13 -- P{s0}[F "d75"] <= P{s0}[F "d74"]
-0.13 -- P{s0}[F "d75"] <= P{s0}[F "d76"]
-0.13 -- P{s0}[F "d76"] <= P{s0}[F "d75"]
-0.13 -- P{s0}[F "d76"] <= P{s0}[F "d77"]
-0.13 -- P{s0}[F "d77"] <= P{s0}[F "d76"]
-0.13 -- P{s0}[F "d77"] <= P{s0}[F "d78"]
-0.13 -- P{s0}[F "d78"] <= P{s0}[F "d77"]
-0.13 -- P{s0}[F "d78"] <= P{s0}[F "d79"]
-0.13 -- P{s0}[F "d79"] <= P{s0}[F "d78"]
-0.13 -- P{s0}[F "d79"] <= P{s0}[F "d0"]
-0.13 -- P{s0}[F "d0"] <= P{s0}[F "d79"]
