ES sched1
E s0(sched1)
Restrict s0 init1
-0.13 -- P{s0}[F "d0"] <= P{s0}[F "d1"]
-0.13 -- P{s0}[F "d1"] <= P{s0}[F "d0"]
-0.13 -- P{s0}[F "d1"] <= P{s0}[F "d2"]
-0.13 -- P{s0}[F "d2"] <= P{s0}[F "d1"]
-0.13 -- P{s0}[F "d2"] <= P{s0}[F "d3"]
-0.13 -- P{s0}[F "d3"] <= P{s0}[F "d2"]
-0.13 -- P{s0}[F "d3"] <= P{s0}[F "d4"]
-0.13 -- P{s0}[F "d4"] <= P{s0}[F "d3"]
-0.13 -- P{s0}[F "d4"] <= P{s0}[F "d5"]
-0.13 -- P{s0}[F "d5"] <= P{s0}[F "d4"]
-0.13 -- P{s0}[F "d5"] <= P{s0}[F "d6"]
-0.13 -- P{s0}[F "d6"] <= P{s0}[F "d5"]
-0.13 -- P{s0}[F "d6"] <= P{s0}[F "d7"]
-0.13 -- P{s0}[F "d7"] <= P{s0}[F "d6"]
-0.13 -- P{s0}[F "d7"] <= P{s0}[F "d8"]
-0.13 -- P{s0}[F "d8"] <= P{s0}[F "d7"]
-0.13 -- P{s0}[F "d8"] <= P{s0}[F "d9"]
-0.13 -- P{s0}[F "d9"] <= P{s0}[F "d8"]
-0.13 -- P{s0}[F "d9"] <= P{s0}[F "d0"]
-0.13 -- P{s0}[F "d0"] <= P{s0}[F "d9"]
